export const CLIENT_DETAILS_REQUEST = "CLIENT_DETAILS_REQUEST";
export const CLIENT_DETAILS_SUCCESS = "CLIENT_DETAILS_SUCCESS";
export const CLIENT_DETAILS_FAIL = "CLIENT_DETAILS_FAIL";
export const CLIENT_DETAILS_RESET = "CLIENT_DETAILS_RESET";

export const CLIENT_UPDATE_PROFILE_REQUEST = "CLIENT_UPDATE_PROFILE_REQUEST";
export const CLIENT_UPDATE_PROFILE_SUCCESS = "CLIENT_UPDATE_PROFILE_SUCCESS";
export const CLIENT_UPDATE_PROFILE_FAIL = "CLIENT_UPDATE_PROFILE_FAIL";
export const CLIENT_UPDATE_PROFILE_RESET = "CLIENT_UPDATE_PROFILE_RESET";

export const CLIENT_SINGLE_DETAILS_REQ = "CLIENT_SINGLE_DETAILS_REQ";
export const CLIENT_SINGLE_DETAILS_SUCCESS = "CLIENT_SINGLE_DETAILS_SUCCESS";
export const CLIENT_SINGLE_DETAILS_FAIL = "CLIENT_SINGLE_DETAILS_FAIL";
export const CLIENT_SINGLE_DETAILS_RESET = "CLIENT_SINGLE_DETAILS_RESET";

export const CLIENT_DEL_REQ = "CLIENT_DEL_REQ";
export const CLIENT_DEL_SUCCESS = "CLIENT_DEL_SUCCESS";
export const CLIENT_DEL_FAIL = "CLIENT_DEL_FAIL";

export const CLIENT_CREATE_REQ = "CLIENT_CREATE_REQ";
export const CLIENT_CREATE_SUCCESS = "CLIENT_CREATE_SUCCESS";
export const CLIENT_CREATE_FAIL = "CLIENT_CREATE_FAIL";
export const CLIENT_CREATE_RESET = "CLIENT_CREATE_RESET";
